In [ ]:
import numpy as np
import matplotlib as plt

In [ ]:
V0 = 0.5
a = 1 
N = 10
x =np.linspace(0,1,N+a)
y = np.linspace(0,1,N+a)
X, Y = np.meshgrid(x,y)
V = np.zeros([N+1, N+1])
V2 = np.zeros([N+1, N+1])
V[:,0] = V0
V2[:,0] = V0
print(V)

n = 0
NN = 100

while n < NN:
    for i in range(1,N):
        for j in range(1,N):
            V2[i,j] = (V[i+1,j] + V[i-1,j] + V[i, j+1] + V[i, j-1]) / 4
    for i in range(1,N):
        for j in range(1,N):
            V[i,j] = V2[i,j]
    n = n + 1

print(V)

plt.contour(X,Y,V, levels =20)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
